#!/bin/bash


OUTFILE=provide_output.txt
NOT_ALLOWED=("${@:1}")

# Submits Incorrect Files. This should fail provide.

function performEdits() {
        i=0
        read -ra num_extra < <(find . -maxdepth 1 -name "extra_file*")
        if [[ "${#num_extra[@]}" -ne 0 ]]; then
                for extra in "${num_extra[@]}";
                do      
                        mv "$extra" "${NOT_ALLOWED[i]}"
                        ((i++))
                done
        else 
                touch "${NOT_ALLOWED[0]}"
        fi
        
}

function performTests() {
        echo -e "~~~~~~~~~~ ${LB}Not Allowed Test${NC} ~~~~~~~~~~~~"
        if grep -q "NOT_OK" $OUTFILE; then
                echo -e "${GRN}Failed to provide. Good!${NC}"
                exit 0
        else
                echo -e "${RED}Something went wrong...${NC}"
                exit 1
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
else
        performEdits
fi
