#!/bin/bash


OUTFILE=provide_output.txt
NOT_ALLOWED=("${@:1}")

# Submits Incorrect Files. This should fail provide.

function performEdits() {
        for file in "${NOT_ALLOWED[@]}"; do
                touch "$file"
        done

}

function performTests() {
        echo -e "~~~~~~~~~~ ${LB}Not Allowed Test${NC} ~~~~~~~~~~~~"
        if grep -q "NOT_OK" $OUTFILE; then
                echo -e "${GRN}Failed to provide. Good!${NC}"
                exit 0
        else
                echo -e "${RED}Submission was accepted. Bad!${NC}"
                exit 1
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
else
        performEdits
fi
