#!/bin/bash


OUTFILE=provide_output.txt
NOT_ALLOWED=("${@:1}")

# Submits Incorrect Files. This should fail provide.

function performEdits() {
        for file in "${NOT_ALLOWED[@]}"; do
                touch "$file"
        done

}

function performTests() {
        echo "~~~~~~~~ Not Allowed Test ~~~~~~~~~~~~"
        if grep -q "NOT_OK" $OUTFILE; then
                echo "Failed to provide. Good!"
                exit 0
        else
                echo "Submission was accepted. Bad!"
                exit 1
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
else
        performEdits
fi
