#!/bin/bash

# Submits Correct Files. This should pass provide and create a valid
# submission.   An error message is displayed if it fails

OUTFILE=provide_output.txt

function performTests() {
        FAIL="This submission doesn't count. Please try again later!"

        echo "~~~~~~~~~   Passing Test ~~~~~~~~~~~~"
        # The test
        if grep -qE "($FAIL|Notify your instructor)" "$OUTFILE"; then
                echo "Submission failed to provide. Bad!"
                exit 1
        else
                echo "Submission was accepted. Good!"
                exit 0
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
fi
