#!/bin/bash

# Submits Correct Files. This should pass provide and create a valid
# submission.   An error message is displayed if it fails

OUTFILE=provide_output.txt

function performTests() {
        FAIL="This submission doesn't count"

        echo -e "~~~~~~~~~~~ ${LB}Passing Test${NC} ~~~~~~~~~~~"
        # The test
        if grep -qE "($FAIL|Notify your instructor)" "$OUTFILE"; then
                echo -e "${RED}Submission failed to provide. Bad!${NC}"
                exit 1
        else
                echo -e "${GRN}Submission was accepted. Good!${NC}"
                exit 0
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
fi
