#!/bin/bash

# Submits Incorrect Files. This should fail provide.

OUTFILE=provide_output.txt

REQUIRED_FILES=("${@:1}")

function performEdits() {
        local num=1
        for file in "${REQUIRED_FILES[@]}"; do
                mv "$file" "bad_file$num.bad"
                ((num++))
        done
}

function performTests() {
        FAIL="NOT_OK"
        FAIL2="This submission doesn't count. Please try again later!"

        echo -e "~~~~~~~~~~ ${LB}Require Test${NC} ~~~~~~~~~~~~"
        # The test
        if grep -qE "($FAIL|$FAIL2)" "$OUTFILE"; then
                echo -e "${GRN}Failed to provide. Good!${NC}"
                exit 0
        else
                echo -e "${RED}Submission was provided. Bad!${NC}"
                exit 1
        fi
}

if [[ "$1" == "--test" ]]; then
        performTests
else
        performEdits
fi
